import Link from "next/link";
import { listArtifacts, artifactUrl } from "@/lib/kb/reader";
import { Breadcrumbs } from "@/components/layout/breadcrumbs";
import { Card, CardContent } from "@/components/ui/card";
import { StatusBadge } from "@/components/artifacts/status-badge";
import { Shield } from "lucide-react";
import type { ArtifactSummary } from "@/lib/kb/types";

export const dynamic = "force-dynamic";

function ReviewCard({ review, type }: { review: ArtifactSummary; type: "CR" | "SR" }) {
  return (
    <Link href={artifactUrl(type, review.id)}>
      <Card className="border-stone-200 bg-white hover:shadow-sm transition-shadow cursor-pointer">
        <CardContent className="py-4 px-4">
          <div className="flex items-center gap-2 mb-2">
            <span className="font-mono text-xs text-stone-400">{review.id}</span>
            {review.metadata["Date"] && (
              <span className="text-xs text-stone-400">{review.metadata["Date"]}</span>
            )}
          </div>
          <h3 className="text-sm font-medium text-stone-800 mb-2">{review.title}</h3>
          <div className="flex items-center gap-2">
            {review.metadata["Target"] && (
              <StatusBadge status={review.metadata["Target"]} />
            )}
            {review.metadata["Scope"] && (
              <StatusBadge status={review.metadata["Scope"]} />
            )}
          </div>
        </CardContent>
      </Card>
    </Link>
  );
}

export default async function ReviewsPage() {
  const [challengeReviews, strategicReviews] = await Promise.all([
    listArtifacts("CR"),
    listArtifacts("SR"),
  ]);

  const isEmpty = challengeReviews.length === 0 && strategicReviews.length === 0;

  return (
    <div>
      <Breadcrumbs items={[{ label: "Dashboard", href: "/" }, { label: "Reviews" }]} />
      <div className="mb-6">
        <h1 className="text-2xl font-semibold text-stone-900 mb-1">Reviews</h1>
        <p className="text-sm text-stone-500">Challenge reviews and strategic reviews</p>
      </div>

      {isEmpty ? (
        <Card className="border-dashed border-stone-300 bg-stone-50/50">
          <CardContent className="py-12 text-center">
            <Shield size={32} className="mx-auto mb-3 text-stone-300" />
            <p className="text-sm text-stone-400">
              No reviews yet. Reviews are generated by the devil&apos;s advocate agent.
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid md:grid-cols-2 gap-6">
          <section>
            <h2 className="text-sm font-semibold text-stone-500 uppercase tracking-wider mb-3">
              Challenge Reviews ({challengeReviews.length})
            </h2>
            <div className="space-y-3">
              {challengeReviews.map((r) => (
                <ReviewCard key={r.id} review={r} type="CR" />
              ))}
              {challengeReviews.length === 0 && (
                <p className="text-sm text-stone-400 text-center py-6">None yet</p>
              )}
            </div>
          </section>
          <section>
            <h2 className="text-sm font-semibold text-stone-500 uppercase tracking-wider mb-3">
              Strategic Reviews ({strategicReviews.length})
            </h2>
            <div className="space-y-3">
              {strategicReviews.map((r) => (
                <ReviewCard key={r.id} review={r} type="SR" />
              ))}
              {strategicReviews.length === 0 && (
                <p className="text-sm text-stone-400 text-center py-6">None yet</p>
              )}
            </div>
          </section>
        </div>
      )}
    </div>
  );
}
